name: Build and Push Secure Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for proper versioning

    - name: Get version from git
      id: version
      run: |
        # Count commits as version number
        VERSION=$(git rev-list --count HEAD)
        SHORT_SHA=$(git rev-parse --short HEAD)
        echo "version=v1.0.${VERSION}" >> $GITHUB_OUTPUT
        echo "sha=${SHORT_SHA}" >> $GITHUB_OUTPUT
        echo "Generated version: v1.0.${VERSION}"

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKER_USERNAME }}/secure-flask-app
        tags: |
          type=raw,value=latest
          type=raw,value=${{ steps.version.outputs.version }}
          type=raw,value=${{ steps.version.outputs.version }}-${{ steps.version.outputs.sha }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: ./python
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}